all:
	g++ main.cpp -o app

4:
	g++ main.cpp -o app
	./app 4

10:
	g++ main.cpp -o app
	./app 10

20:
	g++ main.cpp -o app
	./app 20

40:
	g++ main.cpp -o app
	./app 40

50:
	g++ main.cpp -o app
	./app 50 

clean:
	rm app

